name: Android Build and Upload Debug APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Android SDK
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        distribution: 'sdk'

    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.kts') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Bump version
      run: ./gradlew bumpVersion

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Upload debug APK
      uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/*.apk
